// Generated by CoffeeScript 1.6.3
var demos;

demos = [];

demos.push([
  {
    delay: 750,
    fn: function() {
      return els.body.animate({
        scrollTop: $("#pp-controls").offset().top
      });
    }
  }, {
    delay: 750,
    fn: function() {
      return $("#positions-label").fauxClick();
    }
  }, {
    delay: 750,
    fn: function() {
      return $("[for='input-QB']").fauxClick();
    }
  }, {
    delay: 750,
    fn: function() {
      return $("[for='input-2012']").fauxClick();
    }
  }, {
    delay: 750,
    fn: function() {
      return $("[for='input-2011']").fauxClick();
    }
  }, {
    delay: 750,
    fn: function() {
      return $("[for='input-2010']").fauxClick();
    }
  }, {
    delay: 750,
    fn: function() {
      return $("[for='input-2009']").fauxClick();
    }
  }, {
    delay: 750,
    fn: function() {
      return $("[for='input-2008']").fauxClick();
    }
  }, {
    delay: 750,
    fn: function() {
      return els.body.animate({
        scrollTop: $(".control-row").eq(1).offset().top
      });
    }
  }, {
    delay: 1000,
    fn: function() {
      $("#x-select").trigger("liszt:open");
      return $("#x_select_chzn").fauxClick();
    }
  }, {
    delay: 500,
    fn: function() {
      return $("#x_select_chzn input").typeOut("fantasy position rank", function() {
        return $.noop;
      });
    }
  }, {
    delay: 2000,
    fn: function() {
      $("#y-select").trigger("liszt:open");
      return $("#y_select_chzn").fauxClick();
    }
  }, {
    delay: 500,
    fn: function() {
      return $("#y_select_chzn input").typeOut("fantasy points", function() {
        return $.noop;
      });
    }
  }, {
    delay: 2000,
    fn: function() {
      $("#r-select").trigger("liszt:open");
      return $("#r_select_chzn").fauxClick();
    }
  }, {
    delay: 500,
    fn: function() {
      return $("#r_select_chzn input").typeOut("pass yards", function() {
        return $.noop;
      });
    }
  }, {
    delay: 2000,
    fn: function() {
      $("#c-select").trigger("liszt:open");
      return $("#c_select_chzn").fauxClick();
    }
  }, {
    delay: 500,
    fn: function() {
      return $("#c_select_chzn input").typeOut("season", function() {
        return $.noop;
      });
    }
  }, {
    delay: 1500,
    fn: function() {
      return els.body.animate({
        scrollTop: $("#avg-total-pair-holder").prev("p").offset().top
      });
    }
  }, {
    delay: 750,
    fn: function() {
      return $("#season-label").fauxClick();
    }
  }, {
    delay: 750,
    fn: function() {
      return els.body.animate({
        scrollTop: $("#render-button").offset().top
      });
    }
  }, {
    delay: 750,
    fn: function() {
      return $("#render-button").fauxClick();
    }
  }, {
    delay: 500,
    fn: function() {
      return els.body.animate({
        scrollTop: $("#d3-scatterplot").offset().top
      });
    }
  }
]);

demos.push([
  {
    delay: 750,
    fn: function() {
      return els.body.animate({
        scrollTop: $("#pp-controls").offset().top
      });
    }
  }, {
    delay: 750,
    fn: function() {
      return $("#positions-label").fauxClick();
    }
  }, {
    delay: 750,
    fn: function() {
      return $("[for='input-RB']").fauxClick();
    }
  }, {
    delay: 750,
    fn: function() {
      return $("[for='input-WR']").fauxClick();
    }
  }, {
    delay: 750,
    fn: function() {
      return $("[for='input-2012']").fauxClick();
    }
  }, {
    delay: 750,
    fn: function() {
      return $("[for='input-2011']").fauxClick();
    }
  }, {
    delay: 750,
    fn: function() {
      return $("[for='input-2010']").fauxClick();
    }
  }, {
    delay: 750,
    fn: function() {
      return els.body.animate({
        scrollTop: $(".control-row").eq(1).offset().top
      });
    }
  }, {
    delay: 1000,
    fn: function() {
      $("#x-select").trigger("liszt:open");
      return $("#x_select_chzn").fauxClick();
    }
  }, {
    delay: 500,
    fn: function() {
      return $("#x_select_chzn input").typeOut("fantasy position rank", function() {
        return $.noop;
      });
    }
  }, {
    delay: 2000,
    fn: function() {
      $("#y-select").trigger("liszt:open");
      return $("#y_select_chzn").fauxClick();
    }
  }, {
    delay: 500,
    fn: function() {
      return $("#y_select_chzn input").typeOut("fantasy points", function() {
        return $.noop;
      });
    }
  }, {
    delay: 2000,
    fn: function() {
      $("#r-select").trigger("liszt:open");
      return $("#r_select_chzn").fauxClick();
    }
  }, {
    delay: 500,
    fn: function() {
      return $("#r_select_chzn input").typeOut("total scrimmage yards", function() {
        return $.noop;
      });
    }
  }, {
    delay: 2000,
    fn: function() {
      $("#c-select").trigger("liszt:open");
      return $("#c_select_chzn").fauxClick();
    }
  }, {
    delay: 500,
    fn: function() {
      return $("#c_select_chzn input").typeOut("total touchdowns", function() {
        return $.noop;
      });
    }
  }, {
    delay: 1500,
    fn: function() {
      return els.body.animate({
        scrollTop: $("#avg-total-pair-holder").prev("p").offset().top
      });
    }
  }, {
    delay: 750,
    fn: function() {
      return $("#season-label").fauxClick();
    }
  }, {
    delay: 750,
    fn: function() {
      return els.body.animate({
        scrollTop: $("#render-button").offset().top
      });
    }
  }, {
    delay: 750,
    fn: function() {
      return $("#render-button").fauxClick();
    }
  }, {
    delay: 500,
    fn: function() {
      return els.body.animate({
        scrollTop: $("#d3-scatterplot").offset().top
      });
    }
  }
]);

demos.push([
  {
    delay: 750,
    fn: function() {
      return els.body.animate({
        scrollTop: $("#pp-controls").offset().top
      });
    }
  }, {
    delay: 2000,
    fn: function() {
      $("#player-select").trigger("liszt:open");
      return $("#player_select_chzn").fauxClick();
    }
  }, {
    delay: 500,
    fn: function() {
      return $("#player_select_chzn input").typeOut("Calvin Johnson", function() {
        return $.noop;
      });
    }
  }, {
    delay: 2000,
    fn: function() {
      return $("#player_select_chzn input").typeOut("Julio Jones", function() {
        return $.noop;
      });
    }
  }, {
    delay: 2000,
    fn: function() {
      return $("#player_select_chzn input").typeOut("a.j. green", function() {
        return $.noop;
      });
    }
  }, {
    delay: 500,
    fn: function() {
      return $("#player_select_chzn input").typeOut("Brandon Marshall", function() {
        return $.noop;
      });
    }
  }, {
    delay: 2000,
    fn: function() {
      return $("#player_select_chzn input").typeOut("Mike Wallace", function() {
        return $.noop;
      });
    }
  }, {
    delay: 2000,
    fn: function() {
      return $("#player_select_chzn input").typeOut("Jordy Nelson", function() {
        return $.noop;
      });
    }
  }, {
    delay: 2000,
    fn: function() {
      return $("#player_select_chzn input").typeOut("Dez Bryant", function() {
        return $.noop;
      });
    }
  }, {
    delay: 2000,
    fn: function() {
      return $("#player_select_chzn input").typeOut("Victor Cruz", function() {
        return $.noop;
      });
    }
  }, {
    delay: 2000,
    fn: function() {
      return {
        scrollTop: $(".control-row").eq(1).offset().top
      };
    }
  }, {
    delay: 2000,
    fn: function() {
      $("#x-select").trigger("liszt:open");
      return $("#x_select_chzn").fauxClick();
    }
  }, {
    delay: 500,
    fn: function() {
      return $("#x_select_chzn input").typeOut("receiving yards", function() {
        return $.noop;
      });
    }
  }, {
    delay: 2000,
    fn: function() {
      $("#y-select").trigger("liszt:open");
      return $("#y_select_chzn").fauxClick();
    }
  }, {
    fn: function() {
      return $("#y_select_chzn input").typeOut("receiving touchdowns", function() {
        return $.noop;
      });
    }
  }, {
    delay: 2000,
    fn: function() {
      $("#r-select").trigger("liszt:open");
      return $("#r_select_chzn").fauxClick();
    }
  }, {
    delay: 500,
    fn: function() {
      return $("#r_select_chzn input").typeOut("receptions", function() {
        return $.noop;
      });
    }
  }, {
    delay: 2000,
    fn: function() {
      $("#c-select").trigger("liszt:open");
      return $("#c_select_chzn").fauxClick();
    }
  }, {
    delay: 500,
    fn: function() {
      return $("#c_select_chzn input").typeOut("season", function() {
        return $.noop;
      });
    }
  }, {
    delay: 1500
  }, {
    fn: function() {
      return els.body.animate({
        scrollTop: $("#avg-total-pair-holder").prev("p").offset().top
      });
    }
  }, {
    delay: 750,
    fn: function() {
      return $("#season-label").fauxClick();
    }
  }, {
    delay: 750,
    fn: function() {
      return els.body.animate({
        scrollTop: $("#render-button").offset().top
      });
    }
  }, {
    delay: 750,
    fn: function() {
      return $("#render-button").fauxClick();
    }
  }, {
    delay: 500,
    fn: function() {
      return els.body.animate({
        scrollTop: $("#d3-scatterplot").offset().top
      });
    }
  }
]);
